{
 "title": "master",
 "time": { "from": "2024-03-23T07:53:43.117Z", "to": "2024-03-23T08:21:16.850Z" },
 "panels": [
  {
   "title": "container 개수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace!=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "namespace 개수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "pod 개수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time((sum without()(kube_pod_container_status_ready{namespace=\"kube-system\"}) / count without()(kube_pod_container_status_ready{namespace=\"kube-system\"}))[5m:5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server 요청 개수",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node별 CPU 사용률",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node별 memory 사용률",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{}-node_memory_MemAvailable_bytes{})/node_memory_MemTotal_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽 OUT ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽 IN ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready 상태의 pod 개수",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running 상태의 container 개수",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace!=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod별 CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod별 메모리 사용률",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 27 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container_name!=\"POD\"}) by (pod)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}