{
 "title": "HELLO",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "네임스페이스당 포드 수",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "k8s master node 정상 가동률",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time((sum without()(kube_pod_container_status_ready{namespace=\"kube-system\"}) / count without()(kube_pod_container_status_ready{namespace=\"kube-system\"}))[5m:5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server 요청 개수",
   "type": "stat",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "재시작 된 pod 수 ",
   "type": "bargauge",
   "description": ". Pod 재시작 비율이 높다는 것은 일반적으로 CrashLoopBackOff 를 의미하므로 이는 매우 중요",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "web 파드 수 ",
   "type": "gauge",
   "description": " default 네임스페이스에서 실행 중인 'web' 포드의 수",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"default\", pod=~\".*web.*\", phase=\"Running\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 수 ",
   "type": "stat",
   "description": "각 클러스터에서 사용 가능한 노드 수를 나열",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Worker Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "노드 별 CPU 사용량(%)",
   "type": "gauge",
   "description": "서 이 쿼리는 노드의 모든 CPU 코어가 100% 사용될 때의 유휴 시간 비율을 기반으로 사용률을 추정합니다.\n\n\n노드별 CPU 사용량을 퍼센트로 표현하기 위해서는 각 노드의 사용 가능한 CPU 코어 대비 현재 사용하고 있는 CPU 코어의 비율을 계산해야 합니다. 이를 위해 node_cpu_seconds_total 메트릭의 mode=\"idle\" 값을 사용하여 각 노드에서 사용하지 않고 있는 CPU 시간의 변화율을 구한 다음, 이를 총 CPU 코어 수로 나누고, 결과를 100에서 빼면 사용 중인 CPU의 퍼센트를 얻을 수 있습니다.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 별 memory 사용량(%)",
   "type": "gauge",
   "description": " 각 노드에 대해 사용 가능한 메모리(node_memory_MemAvailable_bytes)를 총 메모리(node_memory_MemTotal_bytes)로 나눈 비율을 계산한 다음, 이 비율을 100에서 빼서 실제 사용 중인 메모리의 퍼센트 비율을 구합니다. avg by (node)는 노드별로 메트릭을 평균내어 각 노드에 대한 결과를 얻기 위해 사용됩니다.\n\n\n이 쿼리는 각 노드에서 사용 가능한 메모리의 비율을 계산하고, 그것을 100에서 빼서 사용 중인 메모리의 비율을 퍼센트로 나타냅니다. 즉, 메모리 사용률을 나타냅니다",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (node) (node_memory_MemAvailable_bytes) / avg by (node) (node_memory_MemTotal_bytes) * 100)\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 별 초당 네트워크 트래픽 IN ",
   "type": "timeseries",
   "description": "노드별로 네트워크 수신 바이트의 합계를 구하려면, 각 노드 이름(node)으로 그룹화하여 rate() 함수를 사용하는 쿼리를 작성해야 합니다",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_receive_bytes_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 별 초당 네트워크 트래픽 OUT ",
   "type": "timeseries",
   "description": " 클러스터 내 모든 노드에서 지난 5분 동안 전송된 네트워크 트래픽의 총 바이트 수의 변화율을 계산합니다. 이는 초당 평균 전송 바이트 수를 의미",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_transmit_bytes_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드별 디스크 읽기 속도",
   "type": "timeseries",
   "description": "디스크 읽기 작업은 저장소 장치로부터 데이터를 읽어오는 과정\n 애플리케이션에서 필요로 하는 데이터를 파일 시스템이나 데이터베이스로부터 가져오는 작업을 말합니다. \"초당 디스크 읽기 바이트\"는 시스템이 저장소로부터 얼마나 많은 데이터를 읽어내는지를 초당 단위로 나타냅니다.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_read_bytes_total[5m]))\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드별 디스크 쓰기 속도 ",
   "type": "timeseries",
   "description": "디스크 쓰기 작업은 데이터를 저장소 장치(디스크)에 기록하는 과정\n, 파일 시스템에 파일을 쓰거나 데이터베이스에 정보를 저장하는 행위가 여기에 해당합니다. 따라서 \"초당 디스크 쓰기 바이트\"는 시스템이 얼마나 많은 데이터를 저장소에 기록하는지를 초당 단위로 측정한 것\n\nnode_disk_written_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_written_bytes_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Web pod ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "web 파드 별 네트워크 트래픽 IN",
   "type": "stat",
   "description": "는 nginx를 이름에 포함하는 모든 파드에서의 네트워크 수신 바이트의 증가율을 5분 간격으로 계산한 후, 이를 파드별로 합산하여 나타냅니다. 이를 통해 각 nginx 파드가 처리하는 네트워크 트래픽의 양을 모니터링할 수 있습니다",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\".*web.*\"}[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "web 파드 별 네트워크 트래픽 OUT",
   "type": "stat",
   "description": "web 가 포함된 파드별로 최근 5분간 네트워크 송신 바이트의 증가율을 합산합니다.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\".*web.*\"}[5m])) by (pod)\r\n\r\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}